Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[19:38:58] [main/INFO] [GradleStart]: Extra: []
[19:38:58] [main/INFO] [GradleStart]: Running with arguments: [--userProperties, {}, --assetsDir, /home/shumaf/.gradle/caches/minecraft/assets, --assetIndex, 1.7.10, --accessToken, {REDACTED}, --version, 1.7.10, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[19:38:58] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[19:38:58] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[19:38:58] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[19:38:58] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[19:38:58] [main/INFO] [FML]: Forge Mod Loader version 7.99.16.1448 for Minecraft 1.7.10 loading
[19:38:58] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Linux:amd64:3.16.0-45-generic, installed at /usr/lib/jvm/java-8-oracle/jre
[19:38:58] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[19:38:58] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:38:59] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:38:59] [main/WARN] [FML]: The coremod thaumcraft.codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:38:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[19:38:59] [main/INFO] [GradleStart]: Injecting location in coremod cpw.mods.fml.relauncher.FMLCorePlugin
[19:38:59] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[19:38:59] [main/INFO] [GradleStart]: Injecting location in coremod codechicken.core.asm.MCPDeobfuscationTransformer.LoadPlugin
[19:38:59] [main/INFO] [GradleStart]: Injecting location in coremod codechicken.core.launch.CodeChickenCorePlugin
[19:38:59] [main/INFO] [GradleStart]: Injecting location in coremod codechicken.nei.asm.NEICorePlugin
[19:38:59] [main/INFO] [GradleStart]: Injecting location in coremod thaumcraft.codechicken.core.launch.DepLoader
[19:38:59] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:38:59] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[19:38:59] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[19:38:59] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:38:59] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:38:59] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:38:59] [main/ERROR] [FML]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[19:39:00] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[19:39:00] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:39:00] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:39:00] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:39:00] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:39:00] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:39:00] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[19:39:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[19:39:01] [main/INFO] [GradleStart]: Remapping AccessTransformer rules...
[19:39:01] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[19:39:01] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[19:39:01] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[19:39:03] [main/INFO]: Setting user: Player294
[19:39:08] [Client thread/INFO]: LWJGL Version: 2.9.1
[19:39:09] [Client thread/INFO] [STDOUT]: [tv.twitch.StandardCoreAPI:<init>:16]: If on Windows, make sure to provide all of the necessary dll's as specified in the twitchsdk README. Also, make sure to set the PATH environment variable to point to the directory containing the dll's.
[19:39:09] [Client thread/ERROR]: Couldn't initialize twitch stream
[19:39:10] [Client thread/INFO] [FML]: Could not load splash.properties, will create a default one
[19:39:10] [Client thread/INFO] [STDOUT]: [cpw.mods.fml.client.SplashProgress:start:188]: ---- Minecraft Crash Report ----
// There are four lights!

Time: 16.08.15 19:39
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.16.0-45-generic
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 918369512 bytes (875 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '2.1 Mesa 10.3.2' Renderer: 'Mesa DRI Intel(R) Ironlake Mobile '
[19:39:10] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[19:39:10] [Client thread/INFO] [FML]: MinecraftForge v10.13.4.1448 Initialized
[19:39:10] [Client thread/INFO] [FML]: Replaced 183 ore recipies
[19:39:11] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[19:39:11] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[19:39:11] [Client thread/INFO] [FML]: Searching /home/shumaf/workspace/Forge/eclipse/mods for mods
[19:39:11] [Client thread/INFO] [FML]: Also searching /home/shumaf/workspace/Forge/eclipse/mods/1.7.10 for mods
[19:39:19] [Client thread/INFO] [FML]: Forge Mod Loader has identified 10 mods to load
[19:39:20] [Client thread/INFO] [FML]: FML has found a non-mod file CodeChickenLib-1.7.10-1.1.1.99-dev.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[19:39:20] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, CodeChickenCore, NotEnoughItems, Animatronics, iChunUtil, Tabula, Thaumcraft, Baubles] at CLIENT
[19:39:20] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, CodeChickenCore, NotEnoughItems, Animatronics, iChunUtil, Tabula, Thaumcraft, Baubles] at SERVER
[19:39:23] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:Animatronics : biomechanic wizardry, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:Tabula, FMLFileResourcePack:Thaumcraft, FMLFileResourcePack:Baubles
[19:39:23] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[19:39:23] [Client thread/INFO] [FML]: Found 341 ObjectHolder annotations
[19:39:23] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[19:39:23] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[19:39:23] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[19:39:29] [Client thread/INFO] [FML]: Applying holder lookups
[19:39:29] [Client thread/INFO] [FML]: Holder lookups applied
[19:39:29] [Client thread/INFO] [FML]: Injecting itemstacks
[19:39:29] [Client thread/INFO] [FML]: Itemstack injection complete
[19:39:29] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[19:39:29] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[19:39:29] [Thread-8/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[19:39:29] [Thread-8/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[19:39:29] [Thread-8/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[19:39:30] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[19:39:30] [Sound Library Loader/INFO]: Sound engine started
[19:39:31] [Client thread/INFO]: Created: 512x512 textures/blocks-atlas
[19:39:32] [Client thread/INFO]: Created: 512x512 textures/items-atlas
[19:39:32] [Client thread/ERROR] [CodeChickenCore]: Unable to do mod description scrolling due to lack of stencil buffer
[19:39:33] [Client thread/INFO] [FML]: Injecting itemstacks
[19:39:33] [Client thread/INFO] [FML]: Itemstack injection complete
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
java: ../../src/xcb_io.c:179: dequeue_pending_request: Проверочное утверждение «!xcb_xlib_unknown_req_in_deq» не выполнено.