<?php
//deklarasi variable
$x=8;
$y=3;
$pertambahan=$x+$y;// berfungsi untuk pertambahan
$pengurangan=$x-$y;// berfungsi untuk pengurangan
$perkalian=$x*$y;// berfungsi untuk perkalian
$pembagian=$x/$y;// berfungsi untuk pembagian
$modulus=$x%$y;// berfungsi untuk modulus/sisa pembagian

echo "Hasil pertambahan $x+$y adalah $pertambahan <br>";
echo "Hasil pengurangan $x-$y adalah $pengurangan <br>";
echo "Hasil perkalian $x*$y adalah $perkalian <br>";
echo "Hasil pembagian $x/$y adalah $pembagian <br>";
echo "Hasil sisa bagi $x%$y adalah $modulus <br>";
?>