function Pos1()
 m.setCursorPos(1,1)
end

function Pos2()
 m.setCursorPos(1,2)
end

function Pos3()
 m.setCursorPos(1,3)
end

function Pos4()
 m.setCursorPos(1,4)
end

function Pos5()
 m.setCursorPos(1,5)
end

function Pos6()
 m.setCursorPos(1,6)
end

function Pos7()
 m.setCursorPos(1,7)
end

function Pos8()
 m.setCursorPos(1,8)
end

function Pos9()
 m.setCursorPos(1,9)
end

function Pos10()
 m.setCursorPos(1,10)
end

--------------------------------------------------

function RSLeftT()
 rs.setOutput(left,true)
end

function RSRightT()
 rs.setOutput(right,true)
end

function RSTopT()
 rs.setOutput(top,true)
end

function RSBackT()
 rs.setOutput(back,true)
end

function RSBotT()
 rs.setOutput(bottom,true)
end

function RSLeftF()
 rs.setOutput(left,false)
end

function RSRightF()
 rs.setOutput(right,false)
end

function RSBackF()
 rs.setOutput(back,false)
end

function RSBotF()
 rs.setOutput(bottom,false)
end

function RSTopF()
 rs.setOutput(top,false)
end

--------------------------------------------------
function BunBkB()
 rs.setBundledOutput(back,black)
end

function BunTpB()
 rs.setBundledOutput(top,black)
end

function BunRtB()
 rs.setBundledOutput(right,black)
end

function BunLtB()
 rs.setBundledOutput(left,black)
end

-------------Red

function BunBkR()
 rs.setOutput(back,red)
end

function BunTpR()
 rs.setOutput(top,red)
end

function BunRtR()
 rs.setOutput(right,red)
end

function BunLtR()
 rs.setOutput(left,red)
end

function BunBot()
 rs.setOutput(bottom,red)
end

------------------Green

function BunBkG()
 rs.setOutput(back,green)
end

function BunTpG()
 rs.setOutput(top,green)
end

function BunRtG()
 rs.setOutput(right,green)
end

function BunLtG()
 rs.setOutput(left,green)
end

function BunBotG()
 rs.setOutput(bottom,green)
end

--------------------Brown

function BunBkBn()
 rs.setOutput(back,brown)
end

function BunTpBn()
 rs.setOutput(top,brown)
end

function BunRtBn()
 rs.setOutput(right,brown)
end

function BunLtBn()
 rs.setOutput(left,brown)
end

function BunBotBn()
 rs.setOutput(bottom,brown)
end

------------------Blue

function BunBkBl()
 rs.setOutput(back,blue)
end

function BunTpBl()
 rs.setOutput(top,blue)
end

function BunRtBl()
 rs.setOutput(right,blue)
end

function BunLtBl()
 rs.setOutput(left,blue)
end

function BunBotBl()
 rs.setOutput(bottom,blue)
end