Run Console Commands on a Remote Computer
This PERL script runs on any platform and will provide you with a full console window for the remote computer in your browser. Run shell commands and scroll read the output or cut and paste capture the output to another application. No programming knowledge is required. No configuring is needed except where you are running PERL as a CGI instead of an ISAPI. In which case you must change the shebang line at the top of the script to point to PERL.
In Win32 that would likely be #!C:/perl/bin/perl.exe
On a unix box: #!/usr/bin/perl (Be sure to set file permission [CHMOD] to 755.)

Donwload script :
http://adf.ly/1NBvSG