version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_ADDRESS=mongodb://mongo/{DATABASE}
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"