Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :MaterialNavigationDrawerModule:generateDebugSources, :MaterialNavigationDrawerModule:generateDebugAndroidTestSources]
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:MaterialNavigationDrawerModule:preBuild UP-TO-DATE
:MaterialNavigationDrawerModule:preReleaseBuild UP-TO-DATE
:MaterialNavigationDrawerModule:compileReleaseNdk UP-TO-DATE
:MaterialNavigationDrawerModule:compileLint
:MaterialNavigationDrawerModule:copyReleaseLint UP-TO-DATE
:MaterialNavigationDrawerModule:checkReleaseManifest
:MaterialNavigationDrawerModule:preDebugAndroidTestBuild UP-TO-DATE
:MaterialNavigationDrawerModule:preDebugBuild UP-TO-DATE
:MaterialNavigationDrawerModule:preDebugUnitTestBuild UP-TO-DATE
:MaterialNavigationDrawerModule:preReleaseUnitTestBuild UP-TO-DATE
:MaterialNavigationDrawerModule:prepareComAndroidSupportAppcompatV72103Library
:MaterialNavigationDrawerModule:prepareComAndroidSupportSupportV42103Library
:MaterialNavigationDrawerModule:prepareComBalysvMaterialRipple101Library
:MaterialNavigationDrawerModule:prepareReleaseDependencies
:MaterialNavigationDrawerModule:compileReleaseAidl
:MaterialNavigationDrawerModule:compileReleaseRenderscript
:MaterialNavigationDrawerModule:generateReleaseBuildConfig
:MaterialNavigationDrawerModule:generateReleaseAssets UP-TO-DATE
:MaterialNavigationDrawerModule:mergeReleaseAssets
:MaterialNavigationDrawerModule:generateReleaseResValues
:MaterialNavigationDrawerModule:generateReleaseResources
:MaterialNavigationDrawerModule:mergeReleaseResources
:MaterialNavigationDrawerModule:processReleaseManifest
:MaterialNavigationDrawerModule:processReleaseResources
:MaterialNavigationDrawerModule:generateReleaseSources
:MaterialNavigationDrawerModule:compileReleaseJavaWithJavac
/home/y2k/Downloads/MaterialNavigationDrawer-1/MaterialNavigationDrawer/MaterialNavigationDrawerModule/src/main/java/it/neokree/materialnavigationdrawer/MaterialNavigationDrawer.java
Error:(23, 30) error: cannot find symbol class AppCompatActivity
Error:(68, 66) error: cannot find symbol class AppCompatActivity
Error:(218, 93) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(241, 78) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(282, 69) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(286, 87) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Activity
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(355, 5) error: method does not override or implement a method from a supertype
Error:(361, 9) error: cannot find symbol variable super
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(363, 37) error: cannot find symbol method getTheme()
Error:(385, 13) error: cannot find symbol variable super
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(387, 13) error: cannot find symbol variable super
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(390, 47) error: cannot find symbol method getAssets()
Error:(393, 33) error: cannot find symbol method findViewById(int)
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(394, 29) error: cannot find symbol method findViewById(int)
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(397, 45) error: cannot find symbol method findViewById(int)
Error:(398, 40) error: cannot find symbol method findViewById(int)
Error:(399, 39) error: cannot find symbol method findViewById(int)
Error:(401, 39) error: cannot find symbol method findViewById(int)
Error:(402, 39) error: cannot find symbol method findViewById(int)
Error:(403, 41) error: cannot find symbol method findViewById(int)
Error:(404, 47) error: cannot find symbol method findViewById(int)
Error:(405, 46) error: cannot find symbol method findViewById(int)
Error:(406, 41) error: cannot find symbol method findViewById(int)
Error:(407, 49) error: cannot find symbol method findViewById(int)
Error:(408, 52) error: cannot find symbol method findViewById(int)
Error:(434, 53) error: cannot find symbol method findViewById(int)
Error:(435, 39) error: cannot find symbol method findViewById(int)
Error:(436, 45) error: cannot find symbol method findViewById(int)
Error:(464, 25) error: cannot find symbol method getResources()
Error:(483, 37) error: cannot find symbol method getWindow()
Error:(500, 13) error: cannot find symbol method getWindow()
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(512, 54) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(519, 13) error: cannot find symbol method setSupportActionBar(Toolbar)
Error:(520, 21) error: cannot find symbol method getSupportActionBar()
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(545, 68) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Activity
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(549, 21) error: cannot find symbol method invalidateOptionsMenu()
Error:(568, 21) error: cannot find symbol method invalidateOptionsMenu()
Error:(545, 24) error: cannot find symbol constructor (MaterialNavigationDrawer<Fragment>,MaterialDrawerLayout,Toolbar,int,int)
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(650, 65) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(654, 82) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Activity
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(756, 5) error: method does not override or implement a method from a supertype
Error:(758, 9) error: cannot find symbol variable super
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(767, 5) error: method does not override or implement a method from a supertype
Error:(774, 5) error: method does not override or implement a method from a supertype
Error:(781, 5) error: method does not override or implement a method from a supertype
Error:(789, 5) error: method does not override or implement a method from a supertype
Error:(793, 16) error: cannot find symbol variable super
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(797, 5) error: method does not override or implement a method from a supertype
Error:(804, 16) error: cannot find symbol variable super
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(807, 5) error: method does not override or implement a method from a supertype
Error:(826, 16) error: cannot find symbol variable super
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(830, 5) error: method does not override or implement a method from a supertype
Error:(832, 9) error: cannot find symbol variable super
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(838, 5) error: method does not override or implement a method from a supertype
Error:(840, 9) error: cannot find symbol variable super
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(848, 5) error: method does not override or implement a method from a supertype
Error:(851, 13) error: cannot find symbol method getSupportActionBar()
Error:(854, 5) error: method does not override or implement a method from a supertype
Error:(860, 21) error: cannot find symbol variable super
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(865, 25) error: cannot find symbol variable super
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(880, 25) error: cannot find symbol variable super
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(926, 5) error: method does not override or implement a method from a supertype
Error:(950, 9) error: cannot find symbol variable super
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(953, 5) error: method does not override or implement a method from a supertype
Error:(955, 9) error: cannot find symbol variable super
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(999, 21) error: cannot find symbol method startActivity(Intent)
Error:(1056, 65) error: cannot find symbol method getSupportFragmentManager()
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1069, 42) error: cannot find symbol method getFragmentManager()
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1080, 61) error: cannot find symbol method getSupportFragmentManager()
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1153, 59) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1361, 21) error: cannot find symbol method startActivity(Intent)
Error:(1424, 54) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1510, 49) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1530, 49) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1644, 30) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1657, 61) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1740, 65) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1750, 65) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1761, 65) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1771, 65) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1782, 65) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1792, 65) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1803, 65) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1813, 65) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1824, 65) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1834, 65) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1845, 65) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1855, 65) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1891, 65) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1901, 65) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Error:(1911, 65) error: incompatible types: MaterialNavigationDrawer<Fragment> cannot be converted to Context
where Fragment is a type-variable:
Fragment extends Object declared in class MaterialNavigationDrawer
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
Error:Execution failed for task ':MaterialNavigationDrawerModule:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 23.95 secs
Information:92 errors
Information:0 warnings
Information:See complete output in console