 Player p2 = getServer().getPlayer(args[0]);
                    ItemStack meta = null;
			        
                    
                    
                    
					p2.getInventory().addItem(new ItemStack (276, 1));
                    p2.getInventory().addItem(new ItemStack (260, 5));
                    p2.getInventory().addItem(new ItemStack (357, 5));
                    p2.getInventory().addItem(new ItemStack (366, 3));
                    p2.getInventory().addItem(new ItemStack (354, 1));