>> Метод: listMethods
Документация: function(filterSource:string?):string -- List all the methods available
>> Метод: doc
Документация: function(method:string):string -- Brief description of method
>> Метод: slot
Документация: -1
>> Метод: getEnergyStored
Документация: function
>> Метод: getMaxEnergyStored
Документация: function
>> Метод: isEnergyProvider
Документация: function():number -- Returns whether this component can provide energy.
>> Метод: getAdvancedMethodsData
Документация: function(method:string?):table -- Get a complete table of information about all available methods
>> Метод: type
Документация: draconic_rf_storage
>> Метод: listSources
Документация: function():table -- List all method sources
>> Метод: isEnergyReceiver
Документация: function():number -- Returns whether this component can receive energy.
>> Метод: address
Документация: 28556e02-b964-4897-962f-42cba65d74ea