12-17 21:50:33.336: I/ActivityManager(4985): START u0 {act=android.intent.action.MAIN typ=null flg=0x10200000 cmp=ComponentInfo{fi.nordea.mep.npay/com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity}} from uid 10330 on display 0
12-17 21:50:33.347: D/ActivityManager(4985): computeStackFocus: New stack r=ActivityRecord{8640acd0 u0 fi.nordea.mep.npay/com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity t-1} stackId=1
12-17 21:50:33.351: D/ActivityManager(4985): moveToFront() : reason=startedActivity setFocusedActivity isAttached=true TaskRecord{45ff1d0 #1045 A=fi.nordea.mep.npay U=0 StackId=1 sz=1}
12-17 21:50:33.357: D/ActivityManager(4985): resumeTopActivityInnerLocked() : #1 prevTask=TaskRecord{45ff1d0 #1045 A=fi.nordea.mep.npay U=0 StackId=1 sz=1} next=ActivityRecord{8640acd0 u0 fi.nordea.mep.npay/com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity t1045} mFocusedStack=ActivityStack{2379ff3d0 stackId=1, 22 tasks}
12-17 21:50:33.362: D/WindowManager(4985): openInputChannel mInputChannel: bc84d4f Starting fi.nordea.mep.npay (server)
12-17 21:50:33.364: V/WindowManager(4985): Relayout Window{bc84d4fd0 u0 Starting fi.nordea.mep.npay}: viewVisibility=0 req=1439x2706 WM.LayoutParams{(0,0)(fillxfill) sim=#20 ty=3 fl=#85830118 pfl=0x20011 wanim=0x7f0d010e vsysui=0x700 needsMenuKey=2 naviIconColor=0}
12-17 21:50:33.384: D/ActivityManager(4985): resumeTopActivityInnerLocked() : #1 prevTask=TaskRecord{7c19af4d0 #972 A=com.teslacoilsw.launcher.NovaLauncher U=0 StackId=0 sz=1} next=ActivityRecord{8640acd0 u0 fi.nordea.mep.npay/com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity t1045} mFocusedStack=ActivityStack{2379ff3d0 stackId=1, 22 tasks}
12-17 21:50:33.386: D/MountService(4985): MountService getExternalStorageMountMode : final mountMode=1, uid : 10376, packageName : fi.nordea.mep.npay
12-17 21:50:33.402: D/WindowManager(4985): finishDrawingWindow: Window{bc84d4fd0 u0 Starting fi.nordea.mep.npay} mDrawState=DRAW_PENDING
12-17 21:50:33.402: I/SELinux(3682): SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=fi.nordea.mep.npay 
12-17 21:50:33.403: I/ActivityManager(4985): Start proc 3682:fi.nordea.mep.npay/u0a376 for activity fi.nordea.mep.npay/com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity
12-17 21:50:33.432: D/ClientCertificateManager Service DD(6442): in isCCMPolicyEnabledForPackage. packageName is fi.nordea.mep.npay
12-17 21:50:33.435: D/ClientCertificateManager Service DD(6442): AdminId - 1000 UserId - 0 packageName - fi.nordea.mep.npay
12-17 21:50:33.436: D/ClientCertificateManager Service DD(6442): in isCCMPolicyEnabledForPackage. packageName is fi.nordea.mep.npay
12-17 21:50:33.438: D/ClientCertificateManager Service DD(6442): AdminId - 1000 UserId - 0 packageName - fi.nordea.mep.npay
12-17 21:50:33.443: I/ActivityManager(4985): DSS on for fi.nordea.mep.npay and scale is 1.0
12-17 21:50:33.454: D/MARsPolicyManager(4985): handlePackageResumedFG pkgName = fi.nordea.mep.npay, userId = 0
12-17 21:50:33.454: D/GameManagerService(4985): handleForegroundChange(). pkgName: fi.nordea.mep.npay, clsName: com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity
12-17 21:50:33.454: D/GameManagerService(4985): notifyResumePause(). pkg: fi.nordea.mep.npay, type: 4, isMinimized: false, isTunableApp: false
12-17 21:50:33.472: D/GamePkgDataHelper(4985): getGamePkgData(). fi.nordea.mep.npay
12-17 21:50:33.474: D/GameManagerService(4985): identifyGamePackage. fi.nordea.mep.npay
12-17 21:50:33.477: D/GameManagerService(4985): identifyGamePackage. fi.nordea.mep.npay
12-17 21:50:33.490: D/GameManagerService(4985): identifyGamePackage. fi.nordea.mep.npay
12-17 21:50:33.493: V/WindowManager(4985): Relayout Window{bc84d4fd0 u0 Starting fi.nordea.mep.npay}: viewVisibility=0 req=1440x2960 WM.LayoutParams{(0,0)(fillxfill) sim=#20 ty=3 fl=#85830118 pfl=0x20011 wanim=0x7f0d010e vsysui=0x700 needsMenuKey=2 naviIconColor=0}
12-17 21:50:33.501: D/GameManagerService(4985): identifyGamePackage. fi.nordea.mep.npay
12-17 21:50:33.607: D/MdnieScenarioControlService(4985):  packageName : fi.nordea.mep.npay    className : com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity
12-17 21:50:33.621: W/System.err(3682): 	at com.nordea.mep.npay.app.PayAppActivity.onCreate(SourceFile:73)
12-17 21:50:33.621: W/System.err(3682): 	at com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity.onCreate(SourceFile:21)
12-17 21:50:33.724: D/AllAroundSensingService(4985): packageName : fi.nordea.mep.npay    className : com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity
12-17 21:50:33.769: D/WindowManager(4985): openInputChannel mInputChannel: cbb990e fi.nordea.mep.npay/com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity (server)
12-17 21:50:33.776: V/WindowManager(4985): Relayout Window{bc84d4fd0 u0 Starting fi.nordea.mep.npay}: viewVisibility=0 req=1440x2960 WM.LayoutParams{(0,0)(fillxfill) sim=#20 ty=3 fl=#85830118 pfl=0x20011 wanim=0x7f0d010e vsysui=0x700 needsMenuKey=2 naviIconColor=0}
12-17 21:50:33.794: V/WindowManager(4985): Relayout Window{cbb990ed0 u0 fi.nordea.mep.npay/com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity}: viewVisibility=0 req=1439x2706 WM.LayoutParams{(0,0)(fillxfill) sim=#120 ty=1 fl=#85810100 pfl=0x20000 wanim=0x7f0d010e vsysui=0x700 needsMenuKey=2 naviIconColor=0}
12-17 21:50:33.828: V/InputMethodManager(3682): Starting input: tba=android.view.inputmethod.EditorInfo@1386494 nm : fi.nordea.mep.npay ic=null
12-17 21:50:33.834: V/InputMethodManagerService(4985): windowGainedFocus: reason=WINDOW_FOCUS_GAIN client=android.os.BinderProxy@ecb12c2 inputContext=null missingMethods= attribute=android.view.inputmethod.EditorInfo@537ff4b nm = fi.nordea.mep.npay controlFlags=#104 softInputMode=#120 windowFlags=#85810100
12-17 21:50:33.839: V/InputMethodManager(3682): Starting input: tba=android.view.inputmethod.EditorInfo@2201b3d nm : fi.nordea.mep.npay ic=null
12-17 21:50:34.020: D/WindowManager(4985): finishDrawingWindow: Window{cbb990ed0 u0 fi.nordea.mep.npay/com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity} mDrawState=DRAW_PENDING
12-17 21:50:34.044: I/ActivityManager(4985): Displayed fi.nordea.mep.npay/com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity: +658ms
12-17 21:50:34.054: D/WindowManager(4985): disposeInputChannel mInputChannel: bc84d4f Starting fi.nordea.mep.npay (server)
12-17 21:50:34.265: I/WindowManager_SurfaceController(4985): Destroying surface Surface(name=Starting fi.nordea.mep.npay) called by com.android.server.wm.WindowStateAnimator.destroySurface:3074 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:1148 com.android.server.wm.WindowState.destroyOrSaveSurface:2771 com.android.server.wm.AppWindowToken.destroySurfaces:434 com.android.server.wm.AppWindowToken.destroySurfaces:398 com.android.server.wm.WindowStateAnimator.finishExit:699 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:583 com.android.server.wm.WindowAnimator.updateWindowsLocked:444 
12-17 21:50:39.909: A/DEBUG(3911): pid: 3682, tid: 3727, name: RenderThread  >>> fi.nordea.mep.npay <<<
12-17 21:50:41.736: W/ActivityManager(4985):   Force finishing activity fi.nordea.mep.npay/com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity
12-17 21:50:41.803: I/WindowManager(4985): WIN DEATH: Window{cbb990ed0 u0 fi.nordea.mep.npay/com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity}
12-17 21:50:41.803: D/WindowManager(4985): disposeInputChannel mInputChannel: cbb990e fi.nordea.mep.npay/com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity (server)
12-17 21:50:41.805: I/ActivityManager(4985): Process fi.nordea.mep.npay (pid 3682) has died(95,618)
12-17 21:50:41.811: I/WindowManager_SurfaceController(4985): Destroying surface Surface(name=fi.nordea.mep.npay/com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:3074 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:1148 com.android.server.wm.WindowState.removeLocked:1934 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:3069 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:3029 com.android.server.wm.WindowManagerService.removeWindowLocked:2994 com.android.server.wm.WindowManagerService.removeWindowLocked:2796 com.android.server.wm.WindowState$DeathRecipient.binderDied:2409 
12-17 21:50:41.833: D/WindowManager(4985): openInputChannel mInputChannel: 6281c43 Application Error: fi.nordea.mep.npay (server)
12-17 21:50:41.850: V/WindowManager(4985): Relayout Window{6281c43d0 u0 Application Error: fi.nordea.mep.npay}: viewVisibility=0 req=1352x558 WM.LayoutParams{(0,0)(wrapxwrap) gr=#11 sim=#120 ty=2003 fl=#1820002 pfl=0x110 fmt=-3 wanim=0x1030392 surfaceInsets=Rect(7, 7 - 7, 7) needsMenuKey=2 dimDuration=150 naviIconColor=0 sfl=0x80000}
12-17 21:50:41.896: D/WindowManager(4985): finishDrawingWindow: Window{6281c43d0 u0 Application Error: fi.nordea.mep.npay} mDrawState=DRAW_PENDING
12-17 21:50:41.900: D/WindowManager(4985): finishDrawingWindow: Window{6281c43d0 u0 Application Error: fi.nordea.mep.npay} mDrawState=COMMIT_DRAW_PENDING
12-17 21:51:03.271: W/ActivityManager(4985): Ignoring remove of inactive process: ProcessRecord{aeb513b 0:fi.nordea.mep.npay/u0a376}
12-17 21:51:03.298: D/WindowManager(4985): disposeInputChannel mInputChannel: 6281c43 Application Error: fi.nordea.mep.npay (server)
12-17 21:51:03.717: I/WindowManager_SurfaceController(4985): Destroying surface Surface(name=Application Error: fi.nordea.mep.npay) called by com.android.server.wm.WindowStateAnimator.destroySurface:3074 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:1148 com.android.server.wm.WindowState.destroyOrSaveSurface:2771 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner:504 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:279 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:227 com.android.server.wm.WindowManagerService$H.handleMessage:9676 android.os.Handler.dispatchMessage:102 
12-17 21:51:03.838: I/ApplicationPackageManager(5588): load=fi.nordea.mep.npay, bg=168-168, dr=168-168, forDefault=false
12-17 21:51:03.839: I/ApplicationPackageManager(5588): load=fi.nordea.mep.npay-theme2, bg=168-168, dr=168-168, tarScale=1.1, relScale=0.88
12-17 21:51:04.126: D/PackageManager(4985): getComponentMetadataForIconTray : com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity does not exist in mServices
12-17 21:51:04.126: D/PackageManager(4985): getComponentMetadataForIconTray : com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity does not exist in mProviders
12-17 21:51:04.126: D/PackageManager(4985): getComponentMetadataForIconTray : com.nordea.mep.npay.feature.splash.presentation.view.SplashActivity does not exist in mReceivers
12-17 21:51:04.130: I/ApplicationPackageManager(1101): load=fi.nordea.mep.npay, bg=144-144, dr=231-231, forDefault=true
12-17 21:51:04.149: I/ApplicationPackageManager(1101): load=fi.nordea.mep.npay-crop, bg=216-216, dr=216-216
12-17 21:51:14.122: D/MountService(4985): MountService getExternalStorageMountMode : final mountMode=1, uid : 10376, packageName : fi.nordea.mep.npay
12-17 21:51:14.147: I/ActivityManager(4985): Start proc 4043:fi.nordea.mep.npay/u0a376 for service fi.nordea.mep.npay/com.urbanairship.job.AirshipGcmTaskService
12-17 21:51:14.155: I/SELinux(4043): SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=fi.nordea.mep.npay 
12-17 21:51:14.218: D/ClientCertificateManager Service DD(6442): in isCCMPolicyEnabledForPackage. packageName is fi.nordea.mep.npay
12-17 21:51:14.228: D/ClientCertificateManager Service DD(6442): AdminId - 1000 UserId - 0 packageName - fi.nordea.mep.npay
12-17 21:51:14.232: D/ClientCertificateManager Service DD(6442): in isCCMPolicyEnabledForPackage. packageName is fi.nordea.mep.npay
12-17 21:51:14.240: D/ClientCertificateManager Service DD(6442): AdminId - 1000 UserId - 0 packageName - fi.nordea.mep.npay
12-17 21:51:14.248: I/ActivityManager(4985): DSS on for fi.nordea.mep.npay and scale is 1.0