{
  "templateName": "centos7-tmp",
  "templateVirtualMachineList": [
    {
      "template": "centos7-tmp",
      "templateSyzyf": [
        {
          "name": "pp_hostname",
          "value": "tomcat-%d"
        },
        {
          "name": "pp_uuid",
          "value": "18c82052-6345-4f3b-b89d-f13a83f8616f"
        },
        {
          "name": "pp_role",
          "value": "syzyf::tomcat"
        },
        {
          "name": "pp_software_version",
          "value": "8.0.44"
        },
        {
          "name": "pp_project",
          "value": "cepik"
        },
        {
          "name": "pp_application",
          "value": "udostępnianie-cep"
        },
        {
          "name": "pp_provisioner",
          "value": "Syzyf 0.0.7-SNAPSHOT"
        }
      ]
    }
  ]
}