{
  "0": {
    "code": 500,
    "message": "Property Billercentral\\NotificationBundle\\Entity\\EmailTemplate::$pdfDownloadName does not exist"
  },
  "1": 500,
  "3": {
    "method": "GET",
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "url": "/proxy/v1/email_templates.json?template_name=invoice_standard&language=DE&product=5",
    "headers": {
      "Accept": "application/json, text/plain, */*"
    }
  }
}