CPU Information
No. CPUs	2
CPU Free	0% 
CPU Used	100% 
Running Processes	99
Load Average (1m)	0.89
Load Average (5m)	11.35
Load Average (15m)	22.59
	Memory
Free Memory	1.22 GB
Used Memory	751 MB
Disk
Free Diskspace	11.9 GB
Used Diskspace	27.6 GB
Total Diskspace	39.5 GB


Server Information
Hostname	xxxxx
Uptime (1 month)	
IP	xxx.xxx.xxx.xxx
Pending Updates	0
Kernel	3.13.0-43-generic
Release Information	Ubuntu 14.04
Location	
Last Update	less than a minute ago
	Network Usage
Connections	176
Net In	250 KBit/s
Net Out	2.85 MBit/s
Net Total	3.1 MBit/s
	
User	PID	PPID	RSS	VSZ	%CPU	%MEM	COMMAND
mysql	29405	1	120 MB	551 MB	13	5	/usr/sbin/mysqld
www	data	21215	29.1 MB	93.1 MB	555564	7	.6 /usr/sbin/apache2 -k start
admin	20892	29815	91.1 MB	540 MB	0	4	/usr/sbin/apache2 -k start
admin	21257	29815	91.4 MB	540 MB	0	4	/usr/sbin/apache2 -k start
admin	21221	29815	76.5 MB	530 MB	0	3	/usr/sbin/apache2 -k start
www	data	20637	29.1 MB	69.4 MB	537744	1	.4 /usr/sbin/apache2 -k start
www	data	21289	29.1 MB	71.8 MB	537204	7	.5 /usr/sbin/apache2 -k start
www	data	20726	29.1 MB	73.8 MB	536548	4	.6 /usr/sbin/apache2 -k start
www	data	20167	29.1 MB	58.7 MB	526308	6	.9 /usr/sbin/apache2 -k start
www	data	21316	29.1 MB	63.2 MB	526052	6	.1 /usr/sbin/apache2 -k start
www	data	21212	29.1 MB	51.4 MB	517160	6	.5 /usr/sbin/apache2 -k start
admin	30003	29815	71.5 MB	456 MB	10	3	/usr/sbin/apache2 -k start
www	data	30175	29.1 MB	4.49 MB	424464	1	.2 /usr/sbin/apache2 -k start
root	29815	1	388 KB	414 MB	0	0	/usr/sbin/apache2 -k start
root	20903	1	19.9 MB	361 MB	0	0	cloudstats-agent 
syslog	787	1	440 KB	250 MB	0	0	rsyslogd
www	data	29818	29.1 MB	124 KB	129232	0	.0 /usr/sbin/apache2 -k start
Debian	1196	1	80 KB	118 MB	0	0	/usr/sbin/exim4 -bd -q30m
root	860	1	0 Bytes	59.9 MB	0	0	/usr/sbin/sshd -D
nginx	7878	7876	1.57 MB	52.9 MB	0	0	nginx: worker process 
nginx	7879	7876	1.59 MB	52.7 MB	0	0	nginx: worker process 
nginx	7880	7876	84 KB	52.1 MB	0	0	nginx: cache manager process 
root	7876	1	32 KB	52.1 MB	0	0	nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf
root	363	1	0 Bytes	50.5 MB	0	0	/lib/systemd/systemd-udevd --daemon
admin	13628	1943	2.76 MB	45.2 MB	0	0	php-fpm: pool www 
admin	563	1943	2.91 MB	45.2 MB	0	0	php-fpm: pool www 
admin	560	1943	2.73 MB	45.2 MB	0	0	php-fpm: pool www 
root	1943	1	56 KB	42 MB	0	0	php-fpm: master process (/usr/local/vesta/php/etc/php-fpm.conf)
admin	1918	1917	2 MB	40.9 MB	0	0	nginx: worker process 
root	1917	1	4 KB	40.3 MB	0	0	nginx: master process /usr/local/vesta/nginx/sbin/vesta-nginx
root	1	0	1.65 MB	32.7 MB	0	0	/sbin/init
root	870	1	156 KB	23.1 MB	0	0	cron
root	645	1	8 KB	23 MB	0	0	/usr/sbin/vsftpd
root	360	1	176 KB	19 MB	0	0	upstart-udev-bridge --daemon
daemon	871	1	0 Bytes	18.7 MB	0	0	atd
root	19067	1	8 KB	15.4 MB	0	0	/sbin/getty -8 38400 tty1
root	839	1	8 KB	15.4 MB	0	0	/sbin/getty -8 38400 tty6
root	835	1	8 KB	15.4 MB	0	0	/sbin/getty -8 38400 tty3
root	834	1	8 KB	15.4 MB	0	0	/sbin/getty -8 38400 tty2
root	829	1	8 KB	15.4 MB	0	0	/sbin/getty -8 38400 tty5
root	826	1	8 KB	15.4 MB	0	0	/sbin/getty -8 38400 tty4
root	30933	20903	1.19 MB	15.3 MB	0	0	ps -eo user,pid,ppid,rss,vsize,pcpu,pmem,command --sort vsize
root	664	1	280 KB	15.3 MB	0	0	upstart-socket-bridge --daemon
root	822	1	324 KB	14.9 MB	0	0	upstart-file-bridge --daemon
root	887	1	0 Bytes	4.26 MB	0	0	acpid -c /etc/acpi/events -s /var/run/acpid.socket
root	28021	2	0 Bytes	0 Bytes	0	0	[kworker/u5:2]
root	20925	2	0 Bytes	0 Bytes	0	0	[kworker/u4:0]
root	20379	2	0 Bytes	0 Bytes	0	0	[kworker/u5:0]
root	13282	2	0 Bytes	0 Bytes	0	0	[kworker/u4:1]
root	4470	2	0 Bytes	0 Bytes	0	0	[kauditd]
root	531	2	0 Bytes	0 Bytes	0	0	[kvm-irqfd-clean]
root	422	2	0 Bytes	0 Bytes	0	0	[ttm_swap]
root	149	2	0 Bytes	0 Bytes	0	0	[kworker/0:2]
root	135	2	0 Bytes	0 Bytes	0	0	[ext4-rsv-conver]
root	134	2	0 Bytes	0 Bytes	0	0	[jbd2/vda1-8]
root	127	2	0 Bytes	0 Bytes	0	0	[kpsmoused]
root	79	2	0 Bytes	0 Bytes	0	0	[charger_manager]
root	78	2	0 Bytes	0 Bytes	0	0	[deferwq]
root	57	2	0 Bytes	0 Bytes	0	0	[scsi_eh_1]
root	56	2	0 Bytes	0 Bytes	0	0	[scsi_eh_0]
root	55	2	0 Bytes	0 Bytes	0	0	[vballoon]
root	53	2	0 Bytes	0 Bytes	0	0	[kthrotld]
root	41	2	0 Bytes	0 Bytes	0	0	[crypto]
root	40	2	0 Bytes	0 Bytes	0	0	[ecryptfs-kthrea]
root	39	2	0 Bytes	0 Bytes	0	0	[fsnotify_mark]
root	38	2	0 Bytes	0 Bytes	0	0	[khugepaged]
root	37	2	0 Bytes	0 Bytes	0	0	[ksmd]
root	36	2	0 Bytes	0 Bytes	16	0	[kswapd0]
root	35	2	0 Bytes	0 Bytes	0	0	[khungtaskd]
root	33	2	0 Bytes	0 Bytes	0	0	[kworker/1:1]
root	32	2	0 Bytes	0 Bytes	0	0	[kworker/0:1]
root	31	2	0 Bytes	0 Bytes	0	0	[devfreq_wq]
root	30	2	0 Bytes	0 Bytes	0	0	[md]
root	29	2	0 Bytes	0 Bytes	0	0	[khubd]
root	28	2	0 Bytes	0 Bytes	0	0	[ata_sff]
root	27	2	0 Bytes	0 Bytes	0	0	[kblockd]
root	25	2	0 Bytes	0 Bytes	0	0	[bioset]
root	24	2	0 Bytes	0 Bytes	0	0	[kintegrityd]
root	23	2	0 Bytes	0 Bytes	0	0	[writeback]
root	22	2	0 Bytes	0 Bytes	0	0	[netns]
root	21	2	0 Bytes	0 Bytes	0	0	[kdevtmpfs]
root	20	2	0 Bytes	0 Bytes	0	0	[khelper]
root	19	2	0 Bytes	0 Bytes	0	0	[kworker/1:0H]
root	18	2	0 Bytes	0 Bytes	0	0	[kworker/1:0]
root	17	2	0 Bytes	0 Bytes	0	0	[ksoftirqd/1]
root	16	2	0 Bytes	0 Bytes	0	0	[migration/1]
root	15	2	0 Bytes	0 Bytes	0	0	[watchdog/1]
root	14	2	0 Bytes	0 Bytes	0	0	[watchdog/0]
root	13	2	0 Bytes	0 Bytes	0	0	[migration/0]
root	12	2	0 Bytes	0 Bytes	0	0	[rcuob/1]
root	11	2	0 Bytes	0 Bytes	0	0	[rcuob/0]
root	10	2	0 Bytes	0 Bytes	0	0	[rcu_bh]
root	9	2	0 Bytes	0 Bytes	0	0	[rcuos/1]
root	8	2	0 Bytes	0 Bytes	0	0	[rcuos/0]
root	7	2	0 Bytes	0 Bytes	0	0	[rcu_sched]
root	5	2	0 Bytes	0 Bytes	0	0	[kworker/0:0H]
root	3	2	0 Bytes	0 Bytes	0	0	[ksoftirqd/0]
root	2	0	0 Bytes	0 Bytes	0	0	[kthreadd]