>java
Oh, sorry about that amnesia. The cold sleep does that some times. Here, let me just get you up to date:

The current year is 2015.
Java has been taken over by one of the most blatantly evil and despised corporations in the world.
The technology and the language are dated and old and literally every other programming language and platform far surpasses it at the things it was designed for.

Look, son, I hate to say this but you need to leave the past behind. You're in the future now. Just embrace it and move on.

>"B-BUT IT'S SO EASY TO LEARN!" yeah, learning how to do things the wrong way is always easy at first... 'till you need to grow up and do something in the adult world. I learned through C/C++ and it wasn't hard. Git gud.
>"b-but it's cross platform!" EVERYTHING is cross platform these days. Holy shit, this isn't 1995.
>"b-but it's open source!" EVERY programming language that is used beyond helloworld is open source. And by the way, apparently Java ISN'T just go read about the Oracle vs. Google lawsuit.
>"b-but it's fast!" That must be why they call it "lagdroid" right? Dumb fuck, garbage collected languages will always be turds when frame rate (performance) matters. Oh? You could pre-allocate all your stuff and just be really careful? WHY NOT USE A REAL SYSTEMS LANGUAGE THEN?
>only JUST FUCKING NOW got lambdas
>truly pathetic performance-- don't make me laugh by pointing to benchmarks which just turn around and call native libs. You're just embarrassing yourselves when you do that because you demonstrate how ignorant you are.
>so insanely verbose it makes C++ seem like a scripting language
>no "auto" or "var" equivalent: http://herbsutter.com/2013/08/12/gotw-94-solution-aaa-style-almost-always-auto/
>no default args for functions
>no tail call optimization
>shitty IDEs that wallow through tasks and take thirty seconds to start up

Holy shit, why do you like punishing yourself?! Cry more fanboys.