Error: Cannot GET /images/ABC123:1yahoo.png
    at raiseUrlNotFoundError (/home/utkarsh/Desktop/prevem/node_modules/loopback/server/middleware/url-not-found.js:15:17)
    at Layer.handle [as handle_request] (/home/utkarsh/Desktop/prevem/node_modules/loopback/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/utkarsh/Desktop/prevem/node_modules/loopback/node_modules/express/lib/router/index.js:312:13)
    at /home/utkarsh/Desktop/prevem/node_modules/loopback/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/utkarsh/Desktop/prevem/node_modules/loopback/node_modules/express/lib/router/index.js:330:12)
    at next (/home/utkarsh/Desktop/prevem/node_modules/loopback/node_modules/express/lib/router/index.js:271:10)
    at /home/utkarsh/Desktop/prevem/node_modules/loopback/node_modules/express/lib/router/index.js:615:15
    at next (/home/utkarsh/Desktop/prevem/node_modules/loopback/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/home/utkarsh/Desktop/prevem/node_modules/loopback/node_modules/express/lib/router/index.js:176:3)
    at router (/home/utkarsh/Desktop/prevem/node_modules/loopback/node_modules/express/lib/router/index.js:46:12)
Error: Cannot GET /ABC123:1yahoo.png
    at raiseUrlNotFoundError (/home/utkarsh/Desktop/prevem/node_modules/loopback/server/middleware/url-not-found.js:15:17)
    at Layer.handle [as handle_request] (/home/utkarsh/Desktop/prevem/node_modules/loopback/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/utkarsh/Desktop/prevem/node_modules/loopback/node_modules/express/lib/router/index.js:312:13)
    at /home/utkarsh/Desktop/prevem/node_modules/loopback/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/utkarsh/Desktop/prevem/node_modules/loopback/node_modules/express/lib/router/index.js:330:12)
    at next (/home/utkarsh/Desktop/prevem/node_modules/loopback/node_modules/express/lib/router/index.js:271:10)
    at /home/utkarsh/Desktop/prevem/node_modules/loopback/node_modules/express/lib/router/index.js:615:15
    at next (/home/utkarsh/Desktop/prevem/node_modules/loopback/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/home/utkarsh/Desktop/prevem/node_modules/loopback/node_modules/express/lib/router/index.js:176:3)
    at router (/home/utkarsh/Desktop/prevem/node_modules/loopback/node_modules/express/lib/router/index.js:46:12)