fringe@fringe-Alienware-17-R2 ~ $ lsmod|pastebinit
The program 'pastebinit' is currently not installed. You can install it by typing:
sudo apt-get install pastebinit
fringe@fringe-Alienware-17-R2 ~ $ sudo apt-get install pastebinit
[sudo] password for fringe: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  pastebinit
0 upgraded, 1 newly installed, 0 to remove and 14 not upgraded.
Need to get 14.9 kB of archives.
After this operation, 168 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main pastebinit all 1.4-3 [14.9 kB]
Fetched 14.9 kB in 0s (26.7 kB/s)   
Selecting previously unselected package pastebinit.
(Reading database ... 165732 files and directories currently installed.)
Preparing to unpack .../pastebinit_1.4-3_all.deb ...
Unpacking pastebinit (1.4-3) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up pastebinit (1.4-3) ...
fringe@fringe-Alienware-17-R2 ~ $ lsmod|pastebinit
Bad API request, invalid api_dev_key
fringe@fringe-Alienware-17-R2 ~ $