127.0.0.1 - - [12/Jan/2018:18:54:37 +0000] "GET //system/uptime HTTP/1.0" 200 34 "-" "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)"
[2018-01-12 18:55:32] [24543] TRACE: Returned module System: Daybo::API::Server::Modules::System=HASH(0x45a70c0)
[2018-01-12 18:55:32] [24543] TRACE: Start time 1515783147, current time 1515783332; calculated uptime 185 seconds
[2018-01-12 18:55:32] [24543] TRACE: $VAR1 = {
          'data' => {
                      'seconds' => 185
                    },
          'error' => 0
        }